# Generated by Django 4.2.7 on 2024-02-13 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timestyle_app', '0002_order_in_cart_order_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'custome user', 'verbose_name_plural': 'custome users'},
        ),
        migrations.RemoveField(
            model_name='designdetails',
            name='description',
        ),
        migrations.AddField(
            model_name='designdetails',
            name='features',
            field=models.TextField(default='Water Resistant'),
        ),
        migrations.AddField(
            model_name='designdetails',
            name='movement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timestyle_app.designdetails'),
        ),
    ]
