name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - dev  # Trigger workflow on push to dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Adjust this as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: python manage.py migrate
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        RAZORPAY_API_KEY: ${{ secrets.RAZORPAY_API_KEY }}
        RAZORPAY_API_SECRET: ${{ secrets.RAZORPAY_API_SECRET }}
        Gpt_Secret_key: ${{ secrets.Gpt_Secret_key }}

    - name: Collect static files
      run: python manage.py collectstatic --noinput
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        RAZORPAY_API_KEY: ${{ secrets.RAZORPAY_API_KEY }}
        RAZORPAY_API_SECRET: ${{ secrets.RAZORPAY_API_SECRET }}
        Gpt_Secret_key: ${{ secrets.Gpt_Secret_key }}

    - name: Deploy to PythonAnywhere
      run: |
        ssh username@ssh.pythonanywhere.com 'cd your_project_directory && git pull origin dev && workon your_virtualenv && python manage.py migrate && python manage.py collectstatic --noinput'
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        RAZORPAY_API_KEY: ${{ secrets.RAZORPAY_API_KEY }}
        RAZORPAY_API_SECRET: ${{ secrets.RAZORPAY_API_SECRET }}
        Gpt_Secret_key: ${{ secrets.Gpt_Secret_key }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
